services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    environment:
      - REDISINSIGHT_AUTH_USERNAME=admin
      - REDISINSIGHT_AUTH_PASSWORD=admin123

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always 

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: degrees_system
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysqldata:/var/lib/mysql
      - ./db-mysql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    ports:
      - "3306:3306"
    restart: always

  application:
    build:
      context: ./application
      dockerfile: ./Dockerfile
    volumes:
      - ./application/storage:/app/storage
    depends_on:
      - mysql
      - rabbitmq
    restart: always

  api_certificate:
    build:
      context: ./api_certificate
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_DATABASE=degrees_system
      - RABBITMQ_HOST=rabbitmq
      - PORT=3000
    volumes:
      - ./application/storage:/app/storage
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "3000:3000"
    restart: always  

volumes:
  mysqldata:
  rabbitmq_data:
  redis_data: